config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'posts/overview' => 'posts#overview'
  resources :posts do
    resources :comments
  end

  get 'about' => 'about#show'

  namespace :admin do
    resources :posts
    root 'posts#index'
  end

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :sessions

  root 'posts#index'

end

app/models/comment.rb
# Note - Ensure that the correct sanitization is used when taking user input
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :name, presence: true, length: { in: 0..30 }
  validates :content, presence: true, length: { in: 3..5000 }
  validates :website, length: { in: 0..50 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { in: 3..50 }
  validates :content, presence: true, length: { in: 3..30000 }

  def self.overview
    all.group_by { |post| post.created_at.month }
       .transform_keys { |ordinal_month| Date::MONTHNAMES[ordinal_month]  }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  def encrypt_password
    return if password.blank?

    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    self.password = nil
  end

  def self.authenticate(email, password)
    user = where(email: email).first
    if user && expected_password?(user, password)
      user
    end
  end

  def self.expected_password?(user, password)
    expected_hash = user.password_hash
    actual_hash = BCrypt::Engine.hash_secret(password, user.password_salt)
    expected_hash == actual_hash
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    before_filter :filter_admin

    def filter_admin
      unless logged_in?
        redirect_to sessions_path
      end
    end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::BaseController
    before_action :set_post, only: [:edit, :update]

    def index
      @posts = Post.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
    end

    def edit
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)

      if @post.save
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new
      end
    end

    def update
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render :edit
      end
    end

    private
      def set_post
        @post = Post.find(params[:id])
      end

      def post_params
        params.require(:post).permit(:title, :content)
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :load_common_view_state

  def load_common_view_state
    @overview = Post.overview
    @current_user = current_user
  end

  def logged_in?
    current_user.present?
  end

  def current_user
    user = User.where(id: user_id).first
    unless user.present?
      self.user_id = nil
    end
    user
  end

  def current_user=(user)
    self.user_id = user.id
  end

  private

  def user_id
    session[:id]
  end

  def user_id=(id)
    session[:id] = id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
                      .tap { |comment| comment.post = @post }

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  private

  def comment_params
    params
      .require(:comment)
      .permit(
          :name,
          :website,
          :content
      )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 3).order(created_at: :desc)
  end

  def overview
    @overview = Post.overview
  end

  def show
    @comment = Comment.new post: @post
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, except: [:destroy]

  def new
  end

  def index
    render :new
  end

  def create
    user = User.authenticate(user_params['email'], user_params['password'])
    if user
      self.current_user = user
      redirect_to admin_posts_path
    else
      flash[:error] = 'Invalid username or password'
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

  private
  def user_params
    params.permit(:email, :password)
  end

  def redirect_if_logged_in
    redirect_to admin_posts_path if logged_in?
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def style_for(path)
    'active' if request.path.starts_with?(path)
  end

  def javascript_include_tag(url, options={})
    x = super(url, options)
  end

  def stylesheet_link_tag(url, options={})
    manifest_file = JSON.parse(File.read('public/assets/production/rev-manifest.json'))

    x = super(url, options)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/about/show.html.haml
%h1 About Alan Foster
%p
  I am a highly enthusiastic and self-motivated individual. I often spend vast amounts of time learning new developmental
  languages.

  I frequently undergo projects in order to acquire a fuller understanding of scripting and programming
  languages, such as recently investigating AngularJS, TypeScript, NodeJs and Scala.
%p
  I enjoy learning via MOOCs, such as Coursera, and I regularly participate in IRC channels, stackoverflow and use GitHub.
%p
  In particular I am passionate about learning new paradigms, programming
  languages, and frameworks. In recent years I have spent time learning some of the following core topics

  %ul
    %li Web Development Frameworks
    %li Compiler Theory
    %li Machine Learning
    %li Functional Programming
%p
  Playing guitar and composing music are also passions of mine. The sense of joy after completing a song is truly
  an overwhelming feeling. Above all I feel inspired when I can show others that which I hath created. Art is also
  a hobby which has allowed for me to show my creativity, technical ability, and aptitude to express myself.

%h1 Current Developments
%p
  A list of the recent projects which I have worked on can be
  found on my #{link_to 'Github page', 'https://github.com/alanfoster'}

app/views/admin/posts/_form.html.haml
%div.new_blog
  -# TODO Why can't we set controller: `Admin::PostsController` or such....
  = semantic_form_for @post, url: (@post.new_record? ? admin_posts_url : admin_post_url(@post)) do |f|
    = f.inputs :title, :content

    = f.actions :submit

app/views/admin/posts/edit.html.haml
%h1 Editing post
= render 'form'
= link_to 'Show', @post
|
= link_to 'Back', admin_posts_path

app/views/admin/posts/index.html.haml
%h1 Listing posts
%table
  %thead
    %tr
      %th Title
      %th Content
      %th Tools
  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.content[0..30] + '...'
        %td
          = link_to 'Show', post
          |
          = link_to 'Edit', edit_admin_post_path(post)
%br
= link_to 'New Post', new_admin_post_path

app/views/admin/posts/new.html.haml
%h1 New post
= render 'form'
= link_to 'Back', posts_path

app/views/comments/_comment.html.haml
%div{class: 'comment ' + cycle('even', 'odd')}
  %div
    %span.name
      = h comment.name
    %span.date
      = comment.created_at.to_formatted_s(:long)
    %div
      = h comment.content

app/views/layouts/_navigation.html.haml
#logo
  Alan Foster
  #links
    - {Blogs: posts_path, About: about_path}.each do |link, path|
      .link
        = link_to link, path, class: style_for(path)
    - if @current_user
      .link
        = link_to 'Admin', admin_posts_url
      .link
        = link_to 'Logout', logout_url

app/views/layouts/_right_content.html.haml
.section
  .heading
    BLOGS
  = render 'posts/overview'

.section
  .heading
    PROGRAMMING
  .link
    %a{:href => "#"} link one
  .link
    %a{:href => "#"} link two
  .link
    %a{:href => "#"} link three
  .link
    %a{:href => "#"} link four
.section
  .heading
    OTHER
  %div{:style => ""}
    = image_tag 'contact.png', alt: 'contact'
    %a{:href => "http://stackoverflow.com/users/551841/alanfoster"}
      %img{:alt => "profile for AlanFoster at Stack Overflow, Q&amp;A for professional and enthusiast programmers", :height => "58", :src => "http://stackoverflow.com/users/flair/551841.png", :title => "profile for AlanFoster at Stack Overflow, Q&amp;A for professional and enthusiast programmers", :width => "208"}

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-22966123-1']);
      _gaq.push(['_setDomainName', '.alanfoster.me']);
      _gaq.push(['_trackPageview']);

      (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    %title Alan Foster Belfast
  %body
    #topBar
    #mainDiv
      #menuArea
        = render 'layouts/navigation'

      #wrapper
        #leftContent
          #innerText
            = yield

        #rightContent
          = render 'layouts/right_content'

        #footer
          %span#createdBy Site created by
          %span#alan
            %a{:href => "http://www.alanfoster.me/"}
              Alan Foster

app/views/posts/_overview.html.haml
- @overview.each do |month, posts|
  %div.blog_grouping
    = month
    %span.bracket
      (
      %span.blogNum> #{posts.count}
      )
    %div.blog_grouping_item
      - posts.each do |post|
        %div
          \- #{link_to post.title, post_path(post)}

app/views/posts/_post.html.haml
%div.post_preview
  %span.title
    = post.title
    - if @current_user
      = link_to '[Edit]', edit_admin_post_path(post)
  %span.date
    = post.created_at.to_formatted_s(:long)
  %div
    != post.content

app/views/posts/_post_preview.html.haml
= render partial: post_preview
%div
  = link_to "#{post_preview.comments.count} comments", post_preview

app/views/posts/edit.html.haml
%h1 Editing post
= render 'form'
= link_to 'Show', @post
|
\#{link_to 'Back', posts_path}

app/views/posts/index.html.haml
%h1 Welcome to Alanfoster.me
= render partial: 'post_preview', collection: @posts
.pagination
  = will_paginate @posts

app/views/posts/overview.html.haml
= render 'overview'

app/views/posts/show.html.haml
= render partial: @post
= render partial: @post.comments

%hr
%div.new_comment
  = semantic_form_for [@post, @comment] do |f|
    = f.inputs :name, :website, :content

    = f.actions :submit